name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  ci:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

      matrix:
        java: [8, 11]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: ./mvnw install -Dmaven.test.skip -Dinvoker.skip

      - name: Run tests
        run: ./mvnw verify -Pintegration-test
